#!/bin/bash
layout="de"
boot="/dev/sdb1"
root="/dev/sdb2"

loadkeys de

cfdisk $target

mkfs.fat "$target"1
mkfs.f2fs "$target"2
mount "$target"2 /mnt
mkdir /mnt/boot
mount "$target"1 /mnt/boot
pacstrap /mnt base linux linux-firmware nano sudo grub dhcpcd networkmanager awesome xorg
genfstab -U /mnt >> /mnt/etc/fstab

cp se /mnt/

arch-chroot /mnt
