#!/bin/bash
layout="de"
boot="/dev/sdb1"
root="/dev/sdb2"

loadkeys de



mkfs.fat $boot
mkfs.f2fs -f $root
mount $root /mnt
mkdir /mnt/boot
mount $boot /mnt/boot
pacstrap /mnt base linux linux-firmware nano sudo grub dhcpcd networkmanager awesome xorg
genfstab -U /mnt >> /mnt/etc/fstab

cp se /mnt/

arch-chroot /mnt
